name: ecosecha_flutter
description: Ecosecha
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  ###########################
  # MODULES

  domain:
    path: domain

  data:
    path: data

  ###########################
  # PLUGINS AND PACKAGES

  intl: any
  cupertino_icons: any
  flutter_bloc: any
  auto_route: any
  equatable: any
  formz: any
  flutter_launcher_icons: any
  cached_network_image: any
  font_awesome_flutter: any
  auto_size_text: any
  url_launcher: any
  awesome_notifications: any
  amplitude_flutter: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: any
  injectable_generator: any
  flutter_lints: any

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.jpeg"