name: ecosecha_flutter
description: Ecosecha
version: 1.0.0+1
environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  auto_route: ^4.0.0
  http: ^0.13.4
  json_annotation: ^4.5.0
  shared_preferences: ^2.0.15
  equatable: ^2.0.3
  formz: ^0.4.0
  flutter_launcher_icons: ^0.9.2
  cached_network_image: ^3.2.1
  font_awesome_flutter: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.10
  json_serializable: ^6.2.0
  injectable_generator: ^1.5.3
  flutter_lints: ^1.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.jpeg"